version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: barpos-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: barpos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: barpos-api
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/barpos?schema=public"
      JWT_SECRET: "supersecret123"
      PORT: 3001
    depends_on:
      - db

volumes:
  postgres_data: